name: normalizer-app

services:
  db:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 2s
      retries: 3

  s3:
    image: minio/minio
    ports:
      - '9010:9000'
      - '9011:9001'
    env_file:
      - .env
    volumes:
      - s3_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 5s
      timeout: 3s
      retries: 2

volumes:
  postgres_data:
  s3_data:
